/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */

plugins {
	`java`
	`application`
}

java {
	toolchain {
		languageVersion.set(JavaLanguageVersion.of(17))
	}
}

sourceSets {
	main {
		java {
			setSrcDirs(listOf("src"))
		}
	}
}

application {
	mainClass.set("vacuumagentproject.VacuumAgentDriver")
}

tasks.register("hello") {
	println("Hello, world!")
}
