#!/usr/bin/env bash
# by Hayden Holbrook <hholbroo@unca.edu>

set -e

pushd ./logs 2>&1 1>/dev/null

for file in *.log; do
    if [[ -f "$file" ]]; then
	echo "Cleaning log $file..."
	# remove date stamp lines and emtpy lines
	sed '/\(Sep\|^$\)/d; s/INFO: //' "$file" >> "$file.cln"
    fi
done

popd 2>&1 1>/dev/null
exit 0
